export const PATHS = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  COURSES: "/courses",
  COURSE_DETAIL: "/courses/:id",
  TESTS: "/tests",
  TEST_TAKE: "/tests/:id/take",
  LEADERBOARD: "/leaderboard",
  ACTIVITY: "/activity",
  QUESTS: "/quests",
  ARENA: "/arena/:id",
  CONTESTS: "/contests",
  MOCK_INTERVIEWS: "/interviews",
  PROFILE: "/profile",
} as const;
